### ISSUE TITLE
Links in "Node.js Implementation" section in README.md broken.

### ISSUE THREAD

**Issue by crowjdh** [reduardo7/sjsClass#2]
These two links below are broken:
https://github.com/reduardo7/sjsClass/blob/master/examples/nodejs-test-global.js
https://github.com/reduardo7/sjsClass/blob/master/examples/nodejs-test-normal.js

**Comment by reduardo7** [comment]
Hi @crowjdh, sorry for the delay, I forgot to check this out! I have added a simple example in `README.md` (https://github.com/reduardo7/sjsClass#nodejs-usage-examples). I hope this helps you.

**Comment by crowjdh** [comment]
Thanks, i'll check out :)
